apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osiris.fullname" . }}-endpoints-hijacker
  labels:
    app.kubernetes.io/name: {{ include "osiris.name" . }}-endpoints-hijacker
    helm.sh/chart: {{ include "osiris.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.endpointsHijacker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "osiris.name" . }}-endpoints-hijacker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "osiris.name" . }}-endpoints-hijacker
        app.kubernetes.io/instance: {{ .Release.Name }}
        releaseRevision: "{{ .Release.Revision }}"
    spec:
      serviceAccountName: {{ include "osiris.fullname" . }}
      imagePullSecrets:
      - name: {{ include "osiris.fullname" . }}
      containers:
      - name: endpoints-hijacker
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          runAsUser: 1000
        command:
        - /osiris/bin/osiris
        args:
        - --logtostderr=true
        - endpoints-hijacker
        env:
        - name: TLS_CERT_FILE
          value: /osiris/cert/tls.crt
        - name: TLS_KEY_FILE
          value: /osiris/cert/tls.key
        ports:
        - name: https
          containerPort: 5000
          protocol: TCP
        livenessProbe:
          httpGet:
            port: https
            scheme: HTTPS
            path: /healthz
        readinessProbe:
          httpGet:
            port: https
            scheme: HTTPS
            path: /healthz
        volumeMounts:
          - name: cert
            mountPath: /osiris/cert
            readOnly: true
        resources:
{{ toYaml .Values.endpointsHijacker.resources | indent 12 }}
    {{- with .Values.endpointsHijacker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.endpointsHijacker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.endpointsHijacker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: cert
        secret:
          secretName: {{ include "osiris.fullname" . }}-endpoints-hijacker-cert
