apiVersion: v1
kind: Service
metadata:
  name: hello-osiris
  labels:
    app: hello-osiris
  annotations:
    osiris.deislabs.io/enabled: "true"
    osiris.deislabs.io/deployment: hello-osiris
    osiris.deislabs.io/loadBalancerHostname: hello-osiris.contoso.io
spec:
  type: LoadBalancer
  ports:
  - name: hello
    port: 80
    targetPort: 4000
  - name: goodbye
    port: 5000
    targetPort: 5000
  selector:
    app: hello-osiris
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-osiris
  labels:
    app: hello-osiris
  annotations:
    osiris.deislabs.io/enabled: "true"
    osiris.deislabs.io/minReplicas: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-osiris
  template:
    metadata:
      labels:
        app: hello-osiris
    spec:
      containers:
      - name: hello-osiris
        image: tariq181290/hello-osiris:0.3.0
        ports:
        - containerPort: 4000
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 4000
        readinessProbe:
          httpGet:
            path: /
            port: 4000
